version: '3'

services:
  cliente-service:
    build:
        context: .
        dockerfile: micro_Cliente/Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cliente-db:5432/cliente-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: gustavo10
    depends_on:
      - cliente-db
    networks:
      - services-app
    restart: on-failure

  cliente-db:
    image: postgres:15.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cliente-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: gustavo10
    volumes:
      - C:\Users\Darwoft\Escritorio\ClientsDB:/var/lib/postgresql/data
    networks:
      - services-app

networks:
  services-app:
    driver: bridge